version: "3.7"
services:
  backend:
    build:
      context: ./newssearch
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
  frontend:
    build:
      context: ./newssearch_ui
      dockerfile: Dockerfile
    ports:
      - '8000:8000'